name: woauto
description: The best app for car owners
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 3.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.8

  get: 4.7.2
  pocketbase: 0.18.1

  google_maps_flutter: 2.13.1
  google_fonts: 6.3.2
  location: 8.0.1
  geocoding: 4.0.0
  geolocator: 14.0.2

  expandable: 5.0.1

  package_info_plus: 8.3.0
  share_plus: 12.0.1
  url_launcher: 6.3.2
  shared_preferences: 2.5.3
  add_2_calendar: 3.0.1
  quick_actions: 1.1.0
  maps_launcher:
    git:
      url: https://github.com/EmreDET/flutter-maps-launcher.git
      tag: master
  app_links: 6.4.1

  image_picker: 1.2.0
  path_provider: 2.1.5
  qr_flutter: 4.1.0
  # timezone: ^0.9.4
  keep_screen_on: 5.0.0

  # Data & Internet
  uuid: 4.5.1

  # UI
  efficient_autocomplete_formfield: 0.3.2+1

  # Languages
  slang: 4.9.2
  slang_flutter: 4.9.0
  animated_digit: 3.3.2
  # Run: `dart run slang`

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  # Run: flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons
      ref: master

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon/back.png"
  adaptive_icon_foreground: "assets/icon/fore.png"
  adaptive_icon_monochrome: "assets/icon/mono.png"

flutter:
  uses-material-design: true

  assets:
    - assets/map_styles/
    - assets/map_styles/dark.json
    - assets/map_styles/light.json
    - assets/
